### ISSUE TITLE
Update vite-plugin-electron to 0.15.4

### ISSUE THREAD

**Issue by codeHusky** [jooy2/vutron#164]
**Describe the bug**
The version of vite-plugin-electron this repo uses by default has a bug where it leaves electron renderers running every time a main/* file is updated and the main app process is restarted

**To Reproduce**
Update any file in src/main/* and use procexp to monitor for stray electron processes at the bottom

**Expected behavior**
All electron renderers close successfully

**Device information (please complete the following information):**
 - OS Name: Windows 
 - OS Version: Win 11

**Screenshots & Attachments**
N/A

**Additional context**
Wasn't able to fix this myself (npm run dev just fails silently after the update for unknown reasons)
tree-kill needs to be installed as a dev dep to fix this as well

**Comment by codeHusky** [comment]
0.15.4 doesn't fix this behavior unfortunately (even after workaround to make it work), will bother vite-plugin-electron

**Comment by codeHusky** [comment]
Actually nvm, this is a valid issue. `tree-kill` needs to be installed as a dev dependency to fix the issue (see vite-plugin-electron readme FAQ). 

The project still fails to start after the vite-plugin-electron update to 0.15.4, not sure why that is causing an issue.

**Comment by codeHusky** [comment]
looks like the no start issue relates to this code change in the new version of the plugin
https://github.com/electron-vite/vite-plugin-electron/compare/v0.14.1...main?diff=unified#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R114
due to `entry` having two options for "main" and then one option for "preload" this check fails. 

removing `'src/main/index.dev.ts'` from the list seems to fix the issue without impacting functionality

**Comment by jooy2** [comment]
Hello. Thank you for using Vutron. And thank you for leaving a detailed description and solution.

Your solution made it easier to figure out the problem, and I've now modified the `index.dev.ts` file to treat it as a separate entry file.
With the changed master, it should also work with the latest version of the `vite-plugin-electron` plugin.

If you run into any other issues, please feel free to open a new issue.
Regards,
