### ISSUE TITLE
The CJS build of Vite's Node API is deprecated.

### ISSUE THREAD

**Issue by DJWezzz** [jooy2/vutron#179]
Hello,

The CJS build of Vite's Node API is deprecated.

Can you change the filename
`vite.config.ts`
 to
`vite.config.mts`?

Even the include in tsconfig.node.json row 12:
`  "include": ["src/main", "src/preload", "package.json", "vite.config.ts", "buildAssets/builder"]`
to
`  "include": ["src/main", "src/preload", "package.json", "vite.config.mts", "buildAssets/builder"]`

**Comment by jooy2** [comment]
Hello, Thank you for using Vutron.

Thank you for reporting the issue. This issue has been resolved in master branch.

Regards,
