### ISSUE TITLE
Could not resolve entry module "src/renderer/src/main/index.ts".

### ISSUE THREAD

**Issue by stark81** [jooy2/vutron#190]
informations:
1.  Mac OS 14.4.1

step:
1. clone the code;
2. yarn add better-sqlite3 and vue-slider-component;
3. yarn run dev

screenshot:
![image](https://github.com/jooy2/vutron/assets/48707376/ebfea4f3-fd7c-4e3f-ba36-da1a97722659)

**Comment by jooy2** [comment]
Hello! Thank you for using `vutron` template.

There was a known issue with the `vite-plugin-electron` module configuration that we are using.
We now have a fix that resolves this issue and has been merged into the `master` branch.

Could you please pull the new changes, or follow the fix below to see if it resolves the issue?
If the issue persists, please reopen this issue.

## Manual workaround
1. Open `vite.config.mts`
2. add `root` option into (`plugins` -> `electronPlugin` -> `vite`) every each keys: `root: resolve('.'),`

![image](https://github.com/jooy2/vutron/assets/48266008/72d1299c-dfbd-4df5-bfcf-86a988c5bc4a)

**Comment by jooy2** [comment]
Since I left the comment, I realized there was one more thing I should have added. I've updated the comment.

Regards,
