### ISSUE TITLE
suggestion: provide an overview of the files in the template

### ISSUE THREAD

**Issue by open768** [jooy2/vutron#29]
**Describe the bug**
Its not a bug :-)

for someone new to electron like me, like me, it would be useful to have in the documenation a section on pointers on the layout of the files in the template and where to begin customising this template.

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**
I love that this works immediately! ive come across a lot of templates that didnt work first time. excellent work!

**Comment by jooy2** [comment]
Hello. Thanks for your feedback!

I added a `project structure` page with a project tree and description attached. Hope this helps:
https://vutron.jooy2.com/project-structure.html

For other information, please check the `Getting Started` page of the documentation page.
Guidelines for beginners will be improved in the future. If you want to correct errors or add content to the documentation, you can always send us a pull request.

Thank you.
