### ISSUE TITLE
add discussions to this git repo

### ISSUE THREAD

**Issue by open768** [jooy2/vutron#46]
Hello this is not a bug.

Please can git discussions be enabled for this repo so that the user community can engage and share ideas without raising issues.
This is easily enabled by ticking the Discussions checkbox under Settings>General>Features

![image](https://user-images.githubusercontent.com/946541/217563223-0b1ada7f-7c74-424d-9c4e-25a4fb849bbb.png)

**Comment by jooy2** [comment]
In fact, I'm not sure how useful discussions will be to many people, but I've decided to enable them for now based on your request.

Thanks for your feedback!
