### ISSUE TITLE
How to inject preload in right way?

### ISSUE THREAD

**Issue by Zen33** [jooy2/vutron#5]
When I set preload value to DEFAULT_WEB_PREFERENCES prop, the client console show error message: electron preload Cannot use import statement outside a module. I resume that the vite  could not compile the preload.js file to es2015 syntax in dist/main folder? Please give a example to this scene, thanks.

**Comment by jooy2** [comment]
Sorry for the confusion. Recently, there was an issue in master where the page did not load correctly after build. A pull to the latest master will solve this problem.

Assuming that the preload file is in the `src/main/preload/index.js` path, you can specify the preload file as shown below.

#### `src/main/utils/Constants.ts`
```typescript
	static DEFAULT_WEB_PREFERENCES = {
		nodeIntegration: true,
		contextIsolation: false,
		nodeIntegrationInWorker: true,
		preload: join(__dirname, './preload/index.js')
	}
```

**Comment by jooy2** [comment]
If the problem 'electron preload Cannot use import statement outside a module' occurs even after applying the above code, you may need to change the code inside the preload script to es module format.

**Comment by Zen33** [comment]
Thanks for the fast reply,  is there a simple and direct way to auto convert preload file to es module? I have tried this you mentioned above, but not work. Finally I added preload file to index.html script tag to solve this temporary.

**Comment by jooy2** [comment]
Hello, Sorry for late reply.

I have included an example of including the `preload.js` (or `.ts`) file when building the latest master code. Can you please check if the problem persists after updating to master code?

The preload script file can be written in `src/preload/index.js` (or `.ts`).

By configuring the entry file separately in the `vite.config.ts` file, scripts can now be imported normally.

There was some confusion in the explanation I left above. Scripts written in `esm` are converted to `cjs` when compiled, so there is no additional script file to work with.

Thanks.

**Comment by Zen33** [comment]
That's very clear, thanks.
