### ISSUE TITLE
Error launching app when adding third party libs in main process

### ISSUE THREAD

**Issue by zeograd** [jooy2/vutron#57]
**Description**
Adding a library in the main process prevents cold start with `npm run dev:debug`.
The problem occurs after the first actual call to the new library and not during hot reload.

**Reproduction**
To reproduce, install a fresh vutron install:
```sh
npm init vutron
cd vutron
yarn install
npm run dev:debug
```

At this point, we have a working clean example, as documented in the quickstart.

Now I add `got` for instance, and call it in ./src/main/index.ts

```sh
yarn install got
vi src/main/index.ts
```

And I add at the end of the import section
```
import got from "got";

got.get("http://google.com").then();
```
At this point, vite recompiles into dist/main and restart electron.

Now, if I stop and restart the `dev:debug` script, it will fail without many explanations.

```sh
^C
npm run dev:debug
# ...
build started... (x2)
✓ 1 modules transformed.
dist/preload/index.js  0.61 kB │ gzip: 0.32 kB
built in 212ms.
transforming (32) node_modules/form-data-encoder/lib/FormDataEncoder.jsError launching app
Unable to find Electron app at /home2/work/vutron

Cannot find module '/home2/work/vutron/dist/main/index.js'. Please verify that the package.json has a valid "main" entry
```

It is correct that there is no such file, the whole dist/main is missing, as if the compilation failed after cleaning the output directory.

**Expected behavior**
I expected that hot reload or cold start of my application behaved the same, without compilation failure on cold start.

**System**
 - OS: linux (debian unstable on amd64)
 - Node: v18.13.0

**Additional context**
This bug seems similar to the previous #7 
I had the same issues with Axios or pdf-lib as third party library.

I don't see how to gather further logs to explain why vite fails in this situation, but I'm available to answer further questions.

Thanks in advance for looking at this issue.

**Comment by jooy2** [comment]
Hello, Thank you for using the `Vutron` template.

Based on your detailed problem description, I was able to successfully reproduce the issue in my Debian environment. Thank you very much.

I don't know the exact cause of this, but we suspect that a build timing issue in the `main` and `preload` scripts is causing the process to crash.

I've published a fix for this issue. I tried the same reproduction method (installing the `got` package) and it was no longer reproduced in the new fix commit.

Sorry to bother you, but can you pull the new code, update it, and try again with yours?

```shell
$ git pull
```

Regards,

**Comment by zeograd** [comment]
Thanks a lot for looking at, and fixing, this issue!

The reproduction steps mentioned in the initial post don't produce the issue on my machine, neither.
And after back porting your vite config file into my larger codebase, it's also fixed there.

Take care
