### ISSUE TITLE
[Feature Request] Please Add a Test Framework

### ISSUE THREAD

**Issue by NotTsunami** [jooy2/vutron#75]
Thank you for creating this template. I have been experimenting with different frameworks when deciding on the framework for my next project and your template has accelerated that research time. One thing that seems a little complex is integrating testing into this specific environment. Especially since this aims to be a production-ready template, I think that it should include a template for testing. Because Spectron is deprecated, I would assume it would use Vitest for writing tests and WebdriverIO to run the tests in an Electron environment.

This is a feature I'm willing to bounty or make a sponsor for. I look forward to hearing your thoughts on this!

**Comment by jooy2** [comment]
Hello. Thank you for using my template and leaving feedback.

I recognize the need for a testing framework, and I'm willing to work on one in the near future.

Currently, I am considering the Playwright solution. However, since Vutron is a template, only the basic functionality and tests of a testing framework will be implemented.

Regards,

**Comment by NotTsunami** [comment]
To me it looks like webdriverio + wdio-electron-service to test Electron and either @testing-library/vue-testing-library or vitest for component-level testing are the best solutions. Only today did I learn how many layers there are to JavaScript testing, and it seems to only get more and more complex the more frameworks you add. It was nice when Spectron was maintained, but unfortunately that's been long deprecated.

**Comment by jooy2** [comment]
Hello.

Thank you for your patience. After much consideration, I have decided to adopt `Playwright`.

Today, I configured a test environment using `Playwright` and incorporated it into the project. Therefore, I'm closing this issue as complete.

If you have any further questions, please join the discussion or create a new issue.

Regards,
